name: Generate PDF using Ruby

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo gem install pdfkit
        sudo gem install wkhtmltopdf-binary
    - name: Run the pdf generation script
      run: |
        ruby ./src/generatepdf.rb
